---
title: " correlation taxa - meta "
author: "Florentin"
date: '`r format(Sys.time(), "%d %B, %Y")`'

output: 
  html_document: 
    toc: yes
    keep_md: yes
---
```{r setup, include=FALSE}
rm(list = ls()) # remove all the object before starting
knitr::opts_chunk$set(echo = TRUE)
```

#### Load required packages

```{r,packages,message=FALSE}
library(tidyverse)
library(phyloseq)
library(speedyseq)
library(ggrepel)
library(ampvis2)
library(plotly)
library(microbiome)
options(getClass.msg=FALSE) # https://github.com/epurdom/clusterExperiment/issues/66
#this fixes an error message that pops up because the class 'Annotated' is defined in two different packages
```

#### Load functions from Github

```{r}
'%!in%' <- function(x,y)!('%in%'(x,y))

source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_taxa_tests.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_normalisation.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_alpha.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_beta.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_heatmap.R")
```


#### Load physeq object


```{r}
ps = "data/processed/physeq_update_11_1_21.RDS"

ps %>% 
  here::here() %>%
  readRDS() %>%
  phyloseq_get_strains_fast() %>%
  phyloseq_remove_chloro_mitho() -> physeq



physeq %>% 
  subset_samples(Experiment == "Continuous") %>% 
  subset_samples(Paul %!in% c("Paul")) %>%
  subset_samples(Reactor != "IR2") -> ps_PolyFermS

```  

We will be analysing only the PolyFermS samples here so take a subset of the physeq object.  
```{r}
physeq %>% 
  subset_samples(Experiment == "Continuous") %>% 
  subset_samples(Paul %!in% c("Paul")) %>%
  subset_samples(Reactor != "IR2") -> ps_polyFermS

sample_data(ps_polyFermS)$Reactor <- fct_relevel(sample_data(ps_polyFermS)$Reactor, "IR1", "CR", "TR1", "TR2","TR3", "TR4", "TR5", "TR6") 

sample_data(ps_polyFermS)$Treatment <- fct_relevel(sample_data(ps_polyFermS)$Treatment, "UNTREATED",  "CTX+HV292.1", "CTX","HV292.1","VAN+CCUG59168", "VAN",  "CCUG59168") 

sample_data(ps_polyFermS)$Reactor_Treatment <- fct_relevel(sample_data(ps_polyFermS)$Reactor_Treatment, "IR1_UNTREATED","CR_UNTREATED", "CR_CTX", "CR_VAN", "TR1_CTX+HV292.1","TR2_CTX", "TR3_HV292.1", "TR5_VAN+CCUG59168", "TR4_VAN", "TR6_CCUG59168") 

ps_polyFermS %>% 
  subset_samples(Enrichment == "NotEnriched") %>%
  rarefy_even_depth(sample.size = 4576,
                    rngseed = 123) -> ps_polyFermS_rare
```


```{r}
"data/raw/hplc Fermentation (Salvato automaticamente).xlsx" %>%
  readxl::read_xlsx(sheet = "All total") -> metabolites
```

```{r}
ps_polyFermS_rare@sam_data %>%
  data.frame() %>%
  rownames_to_column('id') %>%
  left_join(
    metabolites,
    by = c("Sample_description" = "Sample_Id"),
    suffix = c(".x", "")) %>%
  column_to_rownames('id') %>% 
  sample_data() -> ps_polyFermS_rare@sam_data

ps_polyFermS_rare
``` 

```{r, warnings = FALSE, message = FALSE, results = FALSE}
# measures = c("Total_SCFA_mM", "Acetat_mM", "Butyrat_mM", "Propionat_mM", "Isobutyrat_mM", "Valerat_mM", "Isovalerat_mM", "Succinat_mM")
measures = c("Total_SCFA_mM", "Acetat_mM", "Butyrat_mM", "Propionat_mM", "Isobutyrat_mM", "Valerat_mM", "Isovalerat_mM", "Succinat_mM")
```

```{r, warnings = FALSE, message = FALSE, results = FALSE}
ps_polyFermS_rare %>%
  phyloseq_correlate_taxa(log10 = TRUE, 
                          tax_glom = "Class",
                          grouping_column = "Reactor_Treatment", # grouping with fake group column will not subset any data.
                          cor_variables = measures, 
                          method = "spearman",
                          num_taxa = 50,
                          adjustment= 3) -> results
```

```{r, fig.align="center", fig.height=4, fig.width=16, warning = FALSE, message = FALSE, results = FALSE}
results$plot +
  ggpubr::rotate_x_text(60, vjust = 1)
```

```{r, warnings = FALSE, message = FALSE, results = FALSE}
ps_polyFermS_rare %>%
  phyloseq_correlate_taxa(log10 = TRUE, 
                          tax_glom = "Family",
                          grouping_column = "Reactor_Treatment", # grouping with fake group column will not subset any data.
                          cor_variables = measures, 
                          method = "spearman",
                          num_taxa = 50,
                          adjustment= 3) -> results
```

```{r, fig.align="center", fig.height=10, fig.width=16, warning = FALSE, message = FALSE, results = FALSE}
results$plot +
  ggpubr::rotate_x_text(60, vjust = 1)
```

```{r, warnings = FALSE, message = FALSE, results = FALSE}
ps_polyFermS_rare %>%
  phyloseq_correlate_taxa(log10 = TRUE, 
                          tax_glom = "Strain",
                          grouping_column = "Reactor_Treatment", # grouping with fake group column will not subset any data.
                          cor_variables = measures, 
                          method = "spearman",
                          num_taxa = 50,
                          adjustment= 3) -> results
```

```{r, fig.align="center", fig.height=10, fig.width=16, warning = FALSE, message = FALSE, results = FALSE}
results$plot +
  ggpubr::rotate_x_text(60, vjust = 1)
```
```{r}
results$plot$data %>%
  dplyr::filter(AdjPvalue< 0.001 & abs(Correlation) > 0.8) -> tmp

tmp %>%
  dplyr::distinct(Taxa) -> tmp2


tmp2 = "unknown Proteus (Genus) ASV022"
# prune_taxa(tmp2,
#            ps_polyFermS_rare %>% transform_sample_counts(function(x) x/sum(x) * 100)) %>% 
ps_polyFermS_rare %>% transform_sample_counts(function(x) x/sum(x) * 100) %>%
  subset_taxa(Strain %in% c("unknown Proteus (Genus) ASV022")) %>%
  microbiome::transform("log10") %>%
  speedyseq::psmelt() %>%
  dplyr::filter(Reactor == "IR1") -> tmp3


ggstatsplot::ggscatterstats(
  data = tmp3,
  type = "nonparametric",
  x = Isovalerat_mM,
  y = Abundance,
  marginal = FALSE,
  # xlab = "REM sleep (in hours)",
  # ylab = "Amount of time spent awake (in hours)",
  # title = "Understanding mammalian sleep",
  messages = FALSE
) -> p

p
```
```{r}
results$plot$data %>%
  dplyr::filter(AdjPvalue< 0.001 & abs(Correlation) > 0.8) -> tmp

tmp %>%
  dplyr::pull(Taxa) %>%
  unique() -> tmp2

ps_polyFermS_rare %>% #microbiome::transform("clr")  %>%
  subset_taxa(Strain %in% tmp2) %>%
  microbiome::transform("log10") %>%
  speedyseq::psmelt() %>% 
  pivot_wider(names_from = Strain,Sample, 
              values_from =  Abundance ) -> tmp3

ps_polyFermS_rare %>% 
  sample_data() %>% 
  data.frame() %>%
  rownames_to_column('Sample') -> meta


tmp3 %>%
  left_join(meta) %>%
  dplyr::filter(Reactor %in% c("CR1", "TR2", "TR4")) -> tmp3

```

```{r}
my_fn <- function(data, mapping, ...){
  p <- ggplot(data = data, mapping = mapping) + 
    geom_point() + 
    geom_smooth(method=lm, ...)
  p
}

tmp3 %>%
  GGally::ggpairs(columns = c(tmp2, 
                              "Valerat_mM"),
                  ggplot2::aes(colour = Reactor),
                  legend = 1,
                  progress = FALSE,
                  upper = list(
                    continuous = GGally::wrap('cor', method = "spearman")
                  ), 
                  lower = list(continuous = my_fn)) -> corplot
```

```{r, fig.align="center", fig.height=16, fig.width=16, warning = FALSE, message = FALSE, results = FALSE}
corplot  +
  scale_fill_viridis_d() +
  scale_color_viridis_d()
# scale_fill_manual(values = ggpubr::get_palette(palette = "lancet", k = 7)) +
# scale_color_manual(values = ggpubr::get_palette(palette = "lancet", k = 7))
```

```{r, message= FALSE, results= FALSE, warning=FALSE}
ps_polyFermS_rare %>%
  phyloseq_alphas(phylo = TRUE) -> alphas
```

```{r}
my_fn <- function(data, mapping, ...){
  p <- ggplot(data = data, mapping = mapping) + 
    geom_point() + 
    geom_smooth(method=lm, ...)
  p
}

alphas %>%
  GGally::ggpairs(columns = c("Observed", "evenness_pielou", 
                              "diversity_shannon", "SES.MPD", measures),
                  ggplot2::aes(colour = Reactor),
                  legend = 1,
                  progress = FALSE,
                  upper = list(
                    continuous = GGally::wrap('cor', method = "spearman")
                  ), 
                  lower = list(continuous = my_fn)) -> corplot
```

```{r, fig.align="center", fig.height=16, fig.width=16, warning = FALSE, message = FALSE, results = FALSE}
corplot  +
  scale_fill_viridis_d() +
  scale_color_viridis_d()
# scale_fill_manual(values = ggpubr::get_palette(palette = "lancet", k = 7)) +
# scale_color_manual(values = ggpubr::get_palette(palette = "lancet", k = 7))
```


```{r, fig.align="center"}
ps_polyFermS_rare %>%
  microbiome::transform('clr') %>%
  phyloseq::distance(method = "euclidean") -> atchi

ps_polyFermS_rare %>%
  phyloseq_plot_dbrda(dm = atchi,
                    grouping_column="Reactor",
                    pvalueCutoff=0.05,
                    env.variables=measures, 
                    num.env.variables=NULL, 
                    exclude.variables= "Total_SCFA_mM",
                    draw_species=FALSE) -> p

p$plot +scale_color_viridis_d()

p$capscale
```

```{r}
p$capscale %>% 
  vegan::anova.cca()
```

```{r}
p$capscale %>% 
  vegan::anova.cca(by = "margin")
```


```{r}
sessionInfo()
```

