---
title: "Decontamination"
author: "Sneha"
date: "22/10/2020"
output: html_document
---


```{r setup, include=TRUE}
rm(list = ls()) # remove all the object before starting
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages,warning=FALSE,message=FALSE,error=FALSE}
library(tidyverse)
library(phyloseq)
library(speedyseq)
library(ggrepel)
library(decontam)
library(ampvis2)
library(plotly)
require(microDecon)
options(getClass.msg=FALSE) # https://github.com/epurdom/clusterExperiment/issues/66

#this fixes an error message that pops up because the class 'Annotated' is defined in two different packages

```

Load functions from github
```{r}
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_taxa_tests.R") 
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_alpha.R") 
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_beta.R") 
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_heatmap.R")

#function i am altering
source("/Users/snehasundar/Desktop/amchick/metabarcoding analysis_9_10_2020/DivComAnalyses/R/phyloseq_normalisation.R")


```


Load the phyloseq object
```{r}
ps = "/Users/snehasundar/Desktop/amchick/metabarcoding analysis_9_10_2020/physeq_update.RDS"
ps %>% 
  readRDS() -> physeq

#add strain annotation
physeq %>% phyloseq_get_strains -> physeq
``` 

What does the decontam function do

```{r}


  #   taxa_names(physeq)  <- tax_table(physeq)[,"Strain"]
  #   prune_samples(get_variable(physeq,'Experiment')=='NTC',physeq) %>% filter_taxa(function(x) sum(x)>0,prune=TRUE) %>% taxa_names() ->ASV_NTC
  #   
  #    physeq %>%
  #   transform_sample_counts(function(x) x/sum(x) *100)  -> physeq_tmp
  # 
  #      ## export p1 which is a diagnostic plot
  # prune_taxa(ASV_NTC, physeq_tmp) %>% subset_samples(Experiment=='Continuous') %>% 
  #   plot_bar(fill= 'Genus') +
  #   theme(plot.title = element_text(hjust = 0.5)) +
  #   theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 3)) -> p1
  # 
  # p1 + facet_wrap(~Reactor)
  # 
  # 
```
I don't think it it is a good idea to remove all the asvs that are present in ASV because they comprise most of the sample abundances!!!


microDecon

```{r}
physeq %>% otu_table() %>% as.matrix() %>% as.data.frame() %>% rownames_to_column("OTU_ID") -> otu.df


NTC_samples<-physeq %>% subset_samples(Experiment=='NTC') %>% sample_names()

otu.df<-otu.df %>% relocate(all_of(NTC_samples),.after=OTU_ID) 

tax.table<-physeq %>% tax_table() %>% as.matrix() %>% as.data.frame() %>% rownames_to_column('ASV') 
Strain_info <- tax.table$Strain
otu.df<-otu.df %>% mutate(Taxa = Strain_info) %>% rename('taxa'='Taxa')
otu.df
decon(data=otu.df,numb.blanks = 5,numb.ind = 379,taxa = T)
```


