---
title: "NRP72 -metadata - humann - chiken "
author: "Florentin Constancias"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document: 
    toc: yes
    keep_md: yes

---

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)
```

#### Load required packages

```{r,packages,message=FALSE}
library(tidyverse)
library(phyloseq)
library(microbiome)
library(here)
options(getClass.msg=FALSE) # https://github.com/epurdom/clusterExperiment/issues/66
#this fixes an error message that pops up because the class 'Annotated' is defined in two different packages
```


# Import phyloseq object

```{r}
ps = "data/raw/metabarcoding/ps_silva_dada2_human-chicken.RDS"

ps %>% 
  here::here() %>%
  readRDS()  -> physeq

physeq$physeq -> physeq

physeq

```

```{r}
physeq %>% 
  sample_names() %>% 
  sort() %>% 
  head()

```


```{r}
# here::here("data/raw/metabarcoding/merged_chicken_human_04.08.2021.tsv") %>%
here::here("data/raw/metabarcoding/25.11.2021_metadata_updated.tsv") %>%
                        readr::read_tsv() %>% 
  pull("sample") %>% 
  sort() %>% 
  head()

```

```{r, eval=TRUE}
source("https://raw.githubusercontent.com/fconstancias/metabarcodingRpipeline/dev/scripts/functions_export_simplified.R")

# ps@sam_data = NULL

physeq %>%
  physeq_add_metadata(physeq = .,
                      metadata = here::here("data/raw/metabarcoding/25.11.2021_metadata_updated.tsv") %>%
                        readr::read_tsv(), sample_column = "sample") -> physeq_meta




physeq;physeq_meta

```



```{r, eval=TRUE}
source("https://raw.githubusercontent.com/fconstancias/metabarcodingRpipeline/dev/scripts/functions_export_simplified.R")

# ps@sam_data = NULL

physeq %>%
  physeq_add_metadata(physeq = .,
                      metadata = here::here("data/raw/metabarcoding/merged_chicken_human_04.08.2021.tsv") %>%
                        readr::read_tsv() %>% 
    mutate(Reactor_Treatment_Dose = ifelse(!is.na(`Antibiotic_mg/mL`),
       paste0(Reactor_Treatment, `Antibiotic_mg/mL`), Reactor_Treatment),
    Treatment_Dose = ifelse(!is.na(`Antibiotic_mg/mL`),
       paste0(Treatment, `Antibiotic_mg/mL`), Reactor_Treatment))
  , sample_column = "sample") -> physeq_meta


# 
# meta %>% 
#     mutate(Reactor_Treatment_Dose = ifelse(!is.na(`Antibiotic_mg/mL`), 
#        paste0(Reactor_Treatment, `Antibiotic_mg/mL`), Reactor_Treatment)
#     Treatment_Dose = ifelse(!is.na(`Antibiotic_mg/mL`), 
#        paste0(Treatment, `Antibiotic_mg/mL`), Reactor_Treatment))

# ifelse(!is.na(sample_data(physeq_meta)$Antibiotic_mg.mL), 
#        sample_data(physeq_meta)$Antibiotic_mg.mL, "") %>% 
# mutate(gradebook, Pass.Fail = ifelse(grade > 60, "Pass", "Fail"))



physeq;physeq_meta
```

```{r}
physeq_meta %>% 
  saveRDS(here::here("data/raw/metabarcoding/ps_silva_dada2_human_chicken_meta.RDS"))
```

600 samples initially and 471 with metadata ????

```{r}
intersect(
  sample_names(physeq_meta),
  sample_names(physeq)) %>% 
  length()
```

```{r}
difference <- function(x, y) {
c(setdiff(x, y), setdiff(y, x))
}

difference(
  sample_names(physeq),
  sample_names(physeq_meta))
```

Above missing from the metadata but present in the initiall phyloseq object.



```{r}
# physeq_meta %>% 
#   add_phylogeny_to_phyloseq(export = FALSE) %>% 
#   saveRDS(here::here("data/raw/metabarcoding/ps_silva_dada2_humanonly_phylo_meta.RDS"))
```

```{r}
sessionInfo()
```

