---
title: " qPCR "
author: "Florentin"
date: '`r format(Sys.time(), "%d %B, %Y")`'
# knit: (function(inputFile, encoding) {rmarkdown::render(inputFile, encoding = encoding, output_file = paste0(substr(inputFile,1,nchar(inputFile)-4),Sys.Date(),'.html')) })
# knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = paste0('Math-', (format(Sys.Date() - lubridate::wday(Sys.Date() + 1), '%m-%d-%Y')), '.html')) })

output: 
  html_document: 
    toc: yes
    keep_md: yes
---
```{r setup, include=FALSE}
rm(list = ls()) # remove all the object before starting
knitr::opts_chunk$set(echo = TRUE)
```

#### Load required packages

```{r,packages,message=FALSE}
library(tidyverse)
library(phyloseq)
library(speedyseq)
library(ggrepel)
library(ampvis2)
library(plotly)
library(microbiome)
options(getClass.msg=FALSE) # https://github.com/epurdom/clusterExperiment/issues/66
#this fixes an error message that pops up because the class 'Annotated' is defined in two different packages
```

#### Load functions from Github

```{r}
'%!in%' <- function(x,y)!('%in%'(x,y))

source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_taxa_tests.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_normalisation.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_alpha.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_beta.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_heatmap.R")
```


#### Load physeq object


```{r}
ps = "~/Documents/GitHub/amchick/data/processed/physeq_update_23_11.RDS"

ps %>% 
  here::here() %>%
  readRDS() %>%
  phyloseq_get_strains_fast() %>%
  phyloseq_remove_chloro_mitho() -> physeq



physeq %>% 
  subset_samples(Experiment == "Continuous") %>% 
  subset_samples(Paul %!in% c("Paul")) %>%
  subset_samples(Reactor != "IR2") -> ps_PolyFermS

```  

We will be analysing only the PolyFermS samples here so take a subset of the physeq object.  
```{r}
physeq %>% 
  subset_samples(Experiment == "Continuous") %>% 
  subset_samples(Paul %!in% c("Paul")) %>%
  subset_samples(Reactor != "IR2") -> ps_polyFermS

sample_data(ps_polyFermS)$Reactor <- fct_relevel(sample_data(ps_polyFermS)$Reactor, "IR1", "CR", "TR1", "TR2","TR3", "TR4", "TR5", "TR6") 

sample_data(ps_polyFermS)$Treatment <- fct_relevel(sample_data(ps_polyFermS)$Treatment, "UNTREATED",  "CTX+HV292.1", "CTX","HV292.1","VAN+CCUG59168", "VAN",  "CCUG59168") 

sample_data(ps_polyFermS)$Reactor_Treatment <- fct_relevel(sample_data(ps_polyFermS)$Reactor_Treatment, "IR1_UNTREATED","CR_UNTREATED", "CR_CTX", "CR_VAN", "TR1_CTX+HV292.1","TR2_CTX", "TR3_HV292.1", "TR5_VAN+CCUG59168", "TR4_VAN", "TR6_CCUG59168") 

ps_polyFermS %>% 
  rarefy_even_depth(sample.size = 4576,
                    rngseed = 123) -> ps_polyFermS_rare
```


```{r}
sample_data(ps_polyFermS_rare) %>%
  data.frame() -> df
```


Plotting a bar plot of the different diversity indices 
```{r,fig.height=6, fig.width=6, warning = FALSE, message = FALSE, results = FALSE}
measures = c("GeneCopyNumberperML", "HV292.1_Copy_Number_permL", "CCUG59168_Copy_Number_permL", "CTX_Copy_Number_permL","VAN_Copy_Number_permL")

# define a function to plot scatter plot
my_fn <- function(data, mapping, ...){
  p <- ggplot(data = data, mapping = mapping) +
    geom_point() +
    geom_smooth(method=lm, ...)
  p
}


df %>%
  GGally::ggpairs(columns = measures,
                  ggplot2::aes(colour = Reactor),
                  # legend = 1,
                  progress = FALSE,
                  upper = list(
                    continuous = GGally::wrap('cor', method = "spearman")
                  ),
                  lower = list(continuous = my_fn)) -> p_corr

p_corr
```

```{r,fig.align="center"}
df %>%
  plot_alphas(measure = measures,
             x_group = "Reactor_Treatment",
             colour_group = "Enrichment",
             fill_group = "Enrichment",
              shape_group = "Enrichment",
              facet_group = "Reactor_Treatment",
            test_group = "Reactor_Treatment",
            test_group_2 = "Enrichment") -> out
```

```{r}
plot_alpha_time <- function(df, 
                            x = "Day_from_Inoculum", 
                            y = "value", 
                            shape = "neg",
                            fill = "Reactor_Treatment",
                            group = "Reactor_Treatment", 
                            facet)
{
  df %>%
  arrange(Day_from_Inoculum) %>%
  ggplot(aes_string(x = x,
             y = y, shape = shape)) +
  geom_point(size=2, alpha=0.9, aes_string(group = group, color = fill, fill = fill),  show.legend = FALSE) + 
  geom_path(inherit.aes = TRUE, aes_string(group=group),
            size = 0.08,
            linetype = "dashed") +
  facet_grid(as.formula(facet), scales = "free") +
  theme_light() +
  scale_color_viridis_d(na.value = "black") + 
  geom_vline(xintercept = c(23,39), 
             color="black", alpha=0.4) + 
  # geom_smooth(show.legend = TRUE, level = 0.95) + 
  scale_x_continuous(breaks=seq(0,90,10)) -> plot

  return(plot)
}

```

```{r,fig.align="center", warning = FALSE, message = FALSE, results = FALSE}
out$plot$data %>%
  dplyr::filter(Reactor %in% c("IR1", "CR")) %>%
  dplyr::filter(Enrichment == "NotEnriched") %>%
  dplyr::mutate(neg = ifelse(value == 0, "neg", "pos")) %>%
  #dplyr::filter(alphadiversiy %in% c("Observed")) %>% 
  plot_alpha_time(facet = c("Reactor_Treatment ~ alphadiversiy")) + 
  facet_null() + 
  facet_grid(Reactor_Treatment~ alphadiversiy, scales = "fixed") +
  scale_y_log10() +
  geom_smooth(show.legend = FALSE, level = 0.95) +
  ylab("qPCR - copy number / mL") +
  scale_color_manual(values = rep("black",2)) +
  scale_fill_manual(values = rep("black",2))  -> p1

p1 
```

```{r,fig.height=8, fig.width=10, warning = FALSE, message = FALSE, results = FALSE}
out$plot$data %>%
  dplyr::filter(Enrichment == "NotEnriched") %>%
  dplyr::filter(alphadiversiy == "GeneCopyNumberperML") %>%
  dplyr::mutate(neg = ifelse(value == 0, "neg", "pos")) %>%
  plot_alpha_time(facet = c("alphadiversiy ~ Reactor_Treatment")) +
  facet_null() + 
  facet_grid(Reactor_Treatment~ alphadiversiy, scales = "fixed") +
  geom_smooth(show.legend = FALSE, level = 0.95) +
  scale_y_log10() +
  ylab("qPCR - copy number / mL") +
  scale_color_manual(values = rep("black",8)) +
  scale_fill_manual(values = rep("black",8)) -> p2

p2

# p2 %>%
#   plotly::ggplotly()
```

```{r, fig.align="center", fig.height=8, fig.width=14, warning = FALSE, message = FALSE, results = FALSE}
out$plot$data %>%
  dplyr::filter(Enrichment == "NotEnriched") %>%
  dplyr::filter(alphadiversiy %in% c("GeneCopyNumberperML","HV292.1_Copy_Number_permL", "CTX_Copy_Number_permL", "CCUG59168_Copy_Number_permL", "VAN_Copy_Number_permL")) %>%
  dplyr::mutate(alphadiversiy = fct_relevel(alphadiversiy,"GeneCopyNumberperML", "HV292.1_Copy_Number_permL", "CTX_Copy_Number_permL", "CCUG59168_Copy_Number_permL", "VAN_Copy_Number_permL")) %>%
  dplyr::mutate(neg = ifelse(value == 0, "neg", "pos")) %>%
  plot_alpha_time(facet = c("alphadiversiy ~ Reactor_Treatment")) +
  facet_null() +
  facet_grid(alphadiversiy ~ Reactor_Treatment, scales = "fixed") +
  scale_y_log10() +
  geom_smooth(show.legend = FALSE, level = 0.95) +
  scale_shape_manual(values=c(4, 19)) +
  ylab("qPCR - copy number / mL") + 
  scale_color_manual(values = rep("black",8)) +
  scale_fill_manual(values = rep("black",8)) -> p3

p3

```
```{r, fig.align="center", fig.height=8, fig.width=12, warning = FALSE, message = FALSE, results = FALSE}
p3 +
  facet_null() +
  facet_grid(Reactor_Treatment ~ alphadiversiy, scales = "fixed") +
  scale_y_log10() +
  geom_smooth(show.legend = FALSE, level = 0.95) +
  scale_shape_manual(values=c(4, 19)) +
  ylab("qPCR - copy number / mL") +
    scale_color_manual(values = rep("black",8)) +
  scale_fill_manual(values = rep("black",8)) -> p4

p4

```

```{r,fig.align="center", warning = FALSE, message = FALSE, results = FALSE}
out$plot$data %>%
  dplyr::filter(Enrichment == "NotEnriched") %>%
  dplyr::filter(alphadiversiy %in% c("HV292.1_Copy_Number_permL", "CTX_Copy_Number_permL", "CCUG59168_Copy_Number_permL", "VAN_Copy_Number_permL")) %>%
  dplyr::mutate(alphadiversiy = fct_relevel(alphadiversiy,"HV292.1_Copy_Number_permL", "CTX_Copy_Number_permL", "CCUG59168_Copy_Number_permL", "VAN_Copy_Number_permL")) %>%
  dplyr::mutate(neg = ifelse(value == 0, "neg", "pos")) %>%
  plot_alpha_time(facet = c("alphadiversiy ~ Reactor_Treatment")) +
  facet_null() +
  facet_grid(alphadiversiy ~ Reactor_Treatment, scales = "fixed") +
  scale_y_log10() +
  geom_smooth(show.legend = FALSE, level = 0.95) +
  scale_shape_manual(values=c(4, 19)) +
  ylab("qPCR - copy number / mL") +
  scale_color_manual(values = rep("black",8)) +
  scale_fill_manual(values = rep("black",8)) -> p5

p5

```
```{r,fig.align="center", warning = FALSE, message = FALSE, results = FALSE}
out$plot$data %>%
  # dplyr::filter(Enrichment == "NotEnriched") %>%
  dplyr::filter(alphadiversiy %in% c("HV292.1_Copy_Number_permL", "CTX_Copy_Number_permL")) %>%
  dplyr::mutate(alphadiversiy = fct_relevel(alphadiversiy,"HV292.1_Copy_Number_permL", "CTX_Copy_Number_permL")) %>%
  dplyr::mutate(neg = ifelse(value == 0, "neg", "pos")) %>%
  plot_alpha_time(facet = c("alphadiversiy ~ Reactor_Treatment")) +
  facet_null() +
  facet_grid(alphadiversiy + Enrichment ~ Reactor_Treatment , scales = "fixed") +
  scale_y_log10() +
  geom_smooth(show.legend = FALSE, level = 0.95) +
  scale_shape_manual(values=c(4, 19)) +
  ylab("qPCR - copy number / mL") +
  scale_color_manual(values = rep("black",8)) +
  scale_fill_manual(values = rep("black",8)) -> p6

p6 + scale_x_continuous(breaks=seq(0,90,20))

```

```{r,fig.align="center", warning = FALSE, message = FALSE, results = FALSE}
out$plot$data %>%
  # dplyr::filter(Enrichment == "NotEnriched") %>%
  dplyr::filter(alphadiversiy %in% c("CCUG59168_Copy_Number_permL", "VAN_Copy_Number_permL")) %>%
  dplyr::mutate(alphadiversiy = fct_relevel(alphadiversiy,"CCUG59168_Copy_Number_permL", "VAN_Copy_Number_permL")) %>%
  dplyr::mutate(neg = ifelse(value == 0, "neg", "pos")) %>%
  plot_alpha_time(facet = c("alphadiversiy ~ Reactor_Treatment")) +
  facet_null() +
  facet_grid(alphadiversiy + Enrichment ~ Reactor_Treatment , scales = "fixed") +
  scale_y_log10() +
  geom_smooth(show.legend = FALSE, level = 0.95) +
  scale_shape_manual(values=c(4, 19)) +
  ylab("qPCR - copy number / mL") +
  scale_color_manual(values = rep("black",8)) +
  scale_fill_manual(values = rep("black",8)) -> p7

p7 + scale_x_continuous(breaks=seq(0,90,20))

```


```{r}
p2$data %>%
  dplyr::filter(Enrichment == "NotEnriched") %>%
  dplyr::filter(alphadiversiy == "GeneCopyNumberperML") %>%
  dplyr::mutate(neg = ifelse(value == 0, "neg", "pos")) %>%
  arrange(Day_from_Inoculum) %>%
  ggplot(aes_string(x = "Day_from_Inoculum",
             y = "value", group = "Reactor_Treatment")) +
  geom_jitter(size=0.5, alpha=0.9, aes_string(group = "Reactor_Treatment", color = "Reactor_Treatment", fill = "Reactor_Treatment"),  show.legend = TRUE) + 
  geom_path(inherit.aes = TRUE, aes_string(group="Reactor_Treatment", fill = "Reactor_Treatment", color = "Reactor_Treatment", show.legend = FALSE),
            size = 0.008,
            linetype = "dashed") +
  # facet_grid(as.formula(facet), scales = "free") +
  geom_vline(xintercept = c(23,39), 
             color="black", alpha=0.4) + 
  geom_smooth(show.legend = FALSE, level = 0.95, alpha=0.05, size = 0.5 ,aes_string(group="Reactor_Treatment", color = "Reactor_Treatment", fill = "Reactor_Treatment")) +
  scale_x_continuous(breaks=seq(0,90,10)) +
  scale_y_continuous(labels = scientific,
                limits=c(1e+10, 1e+11), breaks = seq(1e+10, 1e+11, by = 1e+10),
                trans = "log10") +
  labs(x="Day (from Inoculum)", y= "qPCR - copy number / mL",  
       col=NULL, fill = NULL, shape = NULL) +
  theme_light() +
  scale_color_viridis_d(na.value = "black") +
  scale_fill_viridis_d(na.value = "black") -> plot

plot + theme(legend.position = "bottom")
```

```{r}
plotly::ggplotly(plot) -> p5ly

p5ly
```

```{r}
htmlwidgets::saveWidget(as_widget(p5ly), 
  paste0(here::here(),
                    "/data/processed/",
       "qPCR_",
       format(Sys.time(), "%Y%b%d"),".html"))
```

```{r}
paste0(here::here(),
       "/data/processed/",
       "qPCR",
       "_",
       format(Sys.time(), "%Y%b%d")
       ,".RData") %>% save.image()
```


```{r}
sessionInfo()
```

