---
title: "NTP72 - CARD 16S beta div"
author: "Florentin Constancias"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document: 
    toc: yes
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# knitr::opts_chunk$set(dev = "ragg_png") # https://ragg.r-lib.org/index.html
knitr::opts_chunk$set(fig.width = 6) #https://r4ds.had.co.nz/graphics-for-communication.html#figure-sizing
knitr::opts_chunk$set(fig.asp = 0.618)
knitr::opts_chunk$set(fig.show = "hold")
knitr::opts_chunk$set(fig.show = "70%")
knitr::opts_chunk$set(fig.align = "center")
```

# Load required packages

```{r,packages,message=FALSE}
library(tidyverse)
# library(phyloseq)
library(speedyseq)
library(ggrepel)
library(here)
# library(microViz)
# library(RColorBrewer)
# library(vegan)
library(randomcoloR)
options(getClass.msg=FALSE) # https://github.com/epurdom/clusterExperiment/issues/66
#this fixes an error message that pops up because the class 'Annotated' is defined in two different packages
```

# Source function

# Source function

```{r message=FALSE}
rm(list = ls())

source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_taxa_tests.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_normalisation.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_alpha.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_beta.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_heatmap.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_varia.R")

```


```{r}
export_ppt = TRUE
export_ppt_width = NULL
export_ppt_height = NULL
out_pptx = here::here("output/plots.pptx")
```

# Import data + cleaning/ colors/ factors:

## Data
### Resistome:
```{r}
"data/processed/resistome/ps_combined_tax_clean.rds" %>% 
  here::here() %>% 
  readRDS() %>% 
  filter_taxa(function(x) sum(x > 0) > 0, TRUE) -> ps_CARD

ps_CARD %>% 
  sample_data() %>% 
  data.frame() %>% 
  select(-input:-index2) %>% 
  mutate(
    Period = case_when(
      Day_of_Treatment == -2 | Day_of_Treatment == -3 | Day_of_Treatment == -6 | Day_of_Treatment == -7 ~ "pret",
      Day_of_Treatment < 10 & Day_of_Treatment >= 0 ~ "t1",
      Day_of_Treatment < 20 & Day_of_Treatment >= 10 ~ "t2",
      Day_of_Treatment < 30 & Day_of_Treatment >= 20 ~ "t3",
      Day_of_Treatment < 40 & Day_of_Treatment >= 30 ~ "t4",
      Day_of_Treatment < 50 & Day_of_Treatment >= 40 ~ "t5",
    )
  ) %>% mutate(Period = base::replace(Period, Treatment == "DONOR", "pret")) -> sample_data(ps_CARD)
```


### 16S:
```{r}
"data/processed/ps_silva_dada2_human_chicken_meta.RDS" %>% 
  here::here() %>% 
  readRDS() %>% 
  subset_samples(Enrichment == "NotEnriched" ) %>% 
  subset_samples(Sample_description %!in% c("TR5-15", "TR4-1")) %>% 
  subset_samples(Day_from_Inoculum >= 30 | Experiment == "Cecum") %>% 
  subset_samples(Experiment != "Batch") %>% 
  subset_samples(is.na(Paul)) %>% 
  subset_samples(Day_of_Treatment >= -4 | Experiment == "Cecum") %>% 
  # %    subset_samples(Model == "Human" & Day_of_Treatment <= 4) %>% 
  filter_taxa(function(x) sum(x > 0) > 0, TRUE) -> ps_16S

# add Day_of_Treatment groups.

ps_16S %>% 
  sample_data() %>% 
  data.frame() %>% 
  mutate(Treatment = base::replace(Treatment, Experiment == "Cecum", "DONOR")) %>%
  # mutate( Treatment  = case_when(Experiment == "Cecum" ~ "DONOR",
  #                               TRUE ~ Treatment)) %>% 
  # mutate(Treatment = ifelse(Experiment == "Cecum", "Donor", Treatment)) %>% 
  mutate(
    Period = case_when(
      Day_of_Treatment == -2 | Day_of_Treatment == -3 | Day_of_Treatment == -6 | Day_of_Treatment == -7 ~ "pret",
      Day_of_Treatment < 10 & Day_of_Treatment >= 0 ~ "t1",
      Day_of_Treatment < 20 & Day_of_Treatment >= 10 ~ "t2",
      Day_of_Treatment < 30 & Day_of_Treatment >= 20 ~ "t3",
      Day_of_Treatment < 40 & Day_of_Treatment >= 30 ~ "t4",
      Day_of_Treatment < 50 & Day_of_Treatment >= 40 ~ "t5",
    )
  ) %>% mutate(Period = base::replace(Period, Treatment == "DONOR", "pret")) -> sample_data(ps_16S)
```

Then:mOTUS, metaphlan, and SQM ORF/genes...


## Metadata_cleaning / uniformisation:

<https://r-graphics.org/recipe-scatter-shapes>

```{r}
# Treatment:
ps_16S %>%
  sample_data() %>%
  data.frame() %>%
  mutate(Treatment = factor(Treatment, levels = sample_data(ps_CARD)$Treatment %>%  levels() )) -> sample_data(ps_16S)

# Antibiotic_mg.mL:
ps_CARD %>%
  sample_data() %>%
  data.frame() %>%
  mutate(Antibiotic_mg.mL = replace_na(Antibiotic_mg.mL, 0)) %>% 
  mutate(Antibiotic_mg.mL = factor(Antibiotic_mg.mL)) -> sample_data(ps_CARD)


ps_16S %>%
  sample_data() %>%
  data.frame() %>%
  mutate(Antibiotic_mg.mL = factor(Antibiotic_mg.mL, levels = sample_data(ps_CARD)$Antibiotic_mg.mL %>%  levels() )) -> sample_data(ps_16S)

# VAN CTX:
ps_CARD %>%
  sample_data() %>%
  data.frame() %>%
  mutate(Antibiotic = factor(Antibiotic, levels = c("CTX", "VAN"))) -> sample_data(ps_CARD)

ps_16S %>%
  sample_data() %>%
  data.frame() %>%
  mutate(Antibiotic = factor(Antibiotic, levels = sample_data(ps_CARD)$Antibiotic %>%  levels() )) -> sample_data(ps_16S)

# VAN Fermentation:
ps_CARD %>%
  sample_data() %>%
  data.frame() %>%
  mutate(Fermentation = replace_na(Fermentation, 1))  %>% 
  mutate(Fermentation = factor(Fermentation, levels = c(1, 2))) -> sample_data(ps_CARD)

ps_16S %>%
  sample_data() %>%
  data.frame() %>%
  mutate(Fermentation = replace_na(Fermentation, 1))  %>% 
  mutate(Fermentation = factor(Fermentation, levels = sample_data(ps_CARD)$Fermentation %>%  levels() )) -> sample_data(ps_16S)



# replace(is.na(.), 0)  %>% 
# mutate(Treatment = replace_na(Antibiotic_mg.mL, 0)) -> sample_data(physeq_AMRgn)
```


## Define astetics:

### Treatment colors:

<https://colorbrewer2.org/#type=diverging&scheme=RdYlBu&n=6>
```{r, out.width = "50%",fig.width = 4.3}  
treat_col <- c("#3CB371", "#7C8181",'#d73027','#fc8d59','#fee090','#4575b4','#91bfdb', '#e0f3f8')

names(treat_col) <- get_variable(ps_CARD, "Treatment") %>%  
  levels()

treat_col %>% 
  scales::show_col(cex_label = 0.5)
```

### Drug classes colors:

```{r, out.width = "50%",fig.width = 4.3}  
ps_CARD %>% 
  generate_color_palette(var = "Drug_Class_multi", seed = 280386) -> drug_classe_multi
```


```{r, out.width = "50%",fig.width = 4.3}  
ps_CARD %>% 
  generate_color_palette(var = "Model_type", pal = "jco") -> model_type

```

```{r, out.width = "50%",fig.width = 4.3}  
ps_CARD %>% 
  generate_color_palette(var = "Resistance_Mechanism_multi",  pal = "npg") -> resistance_type
```

```{r, out.width = "50%",fig.width = 4.3}  
ps_CARD %>% 
  generate_color_palette(var = "AMR_Gene.Family", seed = 72) -> AMR_gene_fam
```

### Others:

<https://r-graphics.org/recipe-scatter-shapes>
```{r}
fermentaion_shape <- c(22, 21)
names(fermentaion_shape) <- sample_data(ps_CARD)$Fermentation %>%  levels()

model_shape <- c(22, 21)
names(model_shape) <- sample_data(ps_CARD)$Model %>%  levels()

antibio_shape <- c(22, 21)
names(antibio_shape) <- sample_data(ps_CARD)$Antibiotic %>%  levels()


conc_stroke <- c(1, 2, 3, 4, 5)
names(conc_stroke) <- sample_data(ps_CARD)$Antibiotic_mg.mL %>%  levels()
# scale_discrete_manual(
#   aesthetics = "stroke",
#   values = c(`A` = 2, `B` = 1, `C` = 2)
# )

theme_set(theme_classic() + theme(legend.position = 'bottom'))
```

<https://r4ds.had.co.nz/graphics-for-communication.html#figure-sizing>

<https://www.tidyverse.org/blog/2020/08/taking-control-of-plot-scaling/>


# Beta-diversity:

```{r}
plot_beta_NRP72 <- function(ps,
                            color = "Treatment", 
                            fill = "Treatment",
                            shape = "Fermentation",
                            alpha = "Antibiotic_mg.mL",
                            label = NA,
                            path_group = "interaction(Model, Fermentation, Reactor_Treatment)",
                            point_size = 2.5,
                            tax_rank_plot = "ASV",
                            taxrank_glom = FALSE,
                            top_r = 10, 
                            fact = 0.4,
                            join_cbind = "cbind"){
  
  #### ----------------------------------------------
  ps %>%
    phyloseq_compute_bdiv(norm = "pc",
                          phylo = FALSE,
                          seed = 123) -> bdiv_list
  
  #### ----------------------------------------------
  
  ps  %>%
    phyloseq_plot_bdiv(dlist = bdiv_list,
                       seed = 123,
                       axis1 = 1,
                       axis2 = 2)  -> pcoa
  

   
  pcoa$wjaccard$layers = NULL
  
  #### ----------------------------------------------
  
  pcoa$wjaccard + geom_point(size= point_size,
                             aes_string(color = color, 
                                        fill = fill,
                                        shape = shape,
                                        alpha = alpha)) + 
    geom_path(arrow = arrow(type = "open", angle = 30, length = unit(0.15, "inches")),
              size = 0.25, linetype = "dashed", inherit.aes = TRUE, aes_string(group = path_group, color = color), show.legend = FALSE) +
    scale_color_manual(name = "", values = treat_col,
                       na.value = "black") +
    scale_fill_manual(name = "", values = treat_col,
                      na.value = "black") +
    scale_shape_manual(name = "" ,values = fermentaion_shape, na.value =  17) +
    scale_alpha_discrete(name = "", range=c(0.6, 1), na.value =  0.6) +
    theme(legend.position = "bottom") + 
    ggrepel::geom_text_repel(cex=2,aes_string(label=label)) -> p_pcoa
  
  #### ----------------------------------------------
  
  # ps %>% 
  #   tax_table() %>% 
  #   data.frame() %>% 
  #   rownames_to_column("id") %>% 
  #   mutate(gene = id) %>% 
  #   column_to_rownames("id") %>% 
  #   as.matrix() %>% 
  #   tax_table() -> tax_table(ps)
  
  #### ----------------------------------------------
  
  
  ps  %>%
    # subset_samples(Treatment != "DONOR") %>% 
    phyloseq_add_taxa_vector(dist = bdiv_list$wjaccard,
                             phyloseq = .,
                             figure_ord = p_pcoa,
                             tax_rank_plot = tax_rank_plot, taxrank_glom = taxrank_glom,
                             top_r = top_r, fact = fact, join_cbind = join_cbind) -> pco_env
  
  # pco_env$plot %>% 
  #   export::graph2ppt(append = TRUE, width = 8, height = 6,
  #                     file = out_pptx)
  
  # p1 + facet_grid(Model ~.)
  #### ----------------------------------------------
  
  return(out = list("pcoa" = p_pcoa,
                    "envfit" = pco_env$plot,
                    "bdiv_list" = bdiv_list))
}
```

## CARD:

### AMRgenes:
```{r, message= FALSE, warning= FALSE}
ps_CARD %>% 
  physeq_simplify_tax(round_otu = FALSE, tax_sel = c("Best_Hit_ARO")) %>% 
  plot_beta_NRP72(path_group = "interaction(Model, Fermentation, Reactor_Treatment)") -> p_b_AMRgn

p_b_AMRgn$pcoa + facet_grid(Model ~.) -> ps_tmp

if(export_ppt == TRUE)
{
  ps_tmp %>% 
    export::graph2ppt(append = TRUE, width = export_ppt_width, height = export_ppt_height,
                      file = out_pptx)
}



p_b_AMRgn$pcoa + facet_grid(Model ~.) -> ps_tmp

ps_tmp

if(export_ppt == TRUE)
{
  ps_tmp %>% 
    export::graph2ppt(append = TRUE, width = export_ppt_width, height = export_ppt_height,
                      file = out_pptx)
}


```


```{r, message= FALSE, warning= FALSE}
ps_CARD %>% 
  subset_samples(Model == "Chicken") %>% 
  physeq_simplify_tax(round_otu = FALSE, tax_sel = c("Best_Hit_ARO")) %>% 
  plot_beta_NRP72(path_group = "interaction(Model, Fermentation, Reactor_Treatment)", label = "Day_of_Treatment") -> p_b_chick_AMRgn

p_b_chick_AMRgn$pcoa + facet_grid(Model ~.) -> ps_tmp

if(export_ppt == TRUE)
{
  ps_tmp %>% 
    export::graph2ppt(append = TRUE, width = export_ppt_width, height = export_ppt_height,
                      file = out_pptx)
}



p_b_chick_AMRgn$envfit + facet_grid(Model ~.) -> ps_tmp

ps_tmp

if(export_ppt == TRUE)
{
  ps_tmp %>% 
    export::graph2ppt(append = TRUE, width = export_ppt_width, height = export_ppt_height,
                      file = out_pptx)
}


```


```{r, message= FALSE, warning= FALSE}
ps_CARD %>% 
  subset_samples(Model == "Human") %>% 
  physeq_simplify_tax(round_otu = FALSE, tax_sel = c("Best_Hit_ARO")) %>% 
  plot_beta_NRP72(path_group = "interaction(Model, Fermentation, Reactor_Treatment)", label = "Day_of_Treatment") -> p_b_chick_AMRgn

p_b_chick_AMRgn$pcoa + facet_grid(Model ~.) -> ps_tmp

if(export_ppt == TRUE)
{
  ps_tmp %>% 
    export::graph2ppt(append = TRUE, width = export_ppt_width, height = export_ppt_height,
                      file = out_pptx)
}



p_b_chick_AMRgn$envfit + facet_grid(Model ~.) -> ps_tmp

ps_tmp

if(export_ppt == TRUE)
{
  ps_tmp %>% 
    export::graph2ppt(append = TRUE, width = export_ppt_width, height = export_ppt_height,
                      file = out_pptx)
}


```

```{r, warning= FALSE , message= FALSE}
ps_CARD %>% 
  subset_samples(Model == "Chicken") %>% 
  physeq_simplify_tax(round_otu = FALSE, tax_sel = c("Best_Hit_ARO")) -> ps_tmp


ps_tmp %>%
  tax_table() %>%
  data.frame() %>%
  rownames_to_column("id") %>%
  mutate(gene = id) %>%
  column_to_rownames("id") %>%
  as.matrix %>%
  tax_table() -> tax_table(ps_tmp)
```

```{r, warning= FALSE , message= FALSE}

# ps_tmp  %>%
#   # subset_samples(Treatment != "DONOR") %>% 
#   phyloseq_add_taxa_vector(dist = p_b_chick_AMRgn$bdiv_list$wjaccard,
#                            phyloseq = .,
#                            figure_ord = p_b_chick_AMRgn$pcoa,
#                            tax_rank_plot = "Drug_Class_multi", taxrank_glom = "Drug_Class_multi",
#                            top_r = 10, fact = 0.6) -> pco_env
# 
# pco_env$signenvfit + facet_grid(Model ~.) -> ps_tmp
# 
# ps_tmp
# 
# if(export_ppt == TRUE)
# {
#   ps_tmp %>% 
#     export::graph2ppt(append = TRUE, width = export_ppt_width, height = export_ppt_height,
#                       file = out_pptx)
# }
# 
# 
# 
# pco_env$plot + facet_grid(Model ~.)

```


### AMR_Gene.Family:
```{r, message= FALSE, warning= FALSE}
# ps_CARD %>% 
#   physeq_simplify_tax(round_otu = FALSE, tax_sel = c("AMR_Gene.Family")) %>% 
#   plot_beta_NRP72(path_group = "interaction(Model, Fermentation, Reactor_Treatment)") -> p_b_AMRgn
# 
# p_b_AMRgn$pcoa + facet_grid(Model ~.) -> ps_tmp
# 
# ps_tmp
# 
# if(export_ppt == TRUE)
# {
#   ps_tmp %>% 
#     export::graph2ppt(append = TRUE, width = export_ppt_width, height = export_ppt_height,
#                       file = out_pptx)
# }
# 

```


## 16S:

```{r, message= FALSE, warning= FALSE}
ps_16S %>% 
  rarefy_even_depth(sample.size = 4576, rngseed = 123) -> ps_16S_rare
```

```{r, message= FALSE, warning= FALSE}
ps_16S_rare %>% 
  plot_beta_NRP72(path_group = "interaction(Model, Fermentation, Reactor_Treatment)", tax_rank_plot = "Family", taxrank_glom = "Family", join_cbind = "join") -> p_b_16S

p_b_16S$pcoa + facet_grid(Model ~.) -> ps_tmp

ps_tmp

if(export_ppt == TRUE)
{
  ps_tmp %>% 
    export::graph2ppt(append = TRUE, width = export_ppt_width, height = export_ppt_height,
                      file = out_pptx)
}

p_b_16S$envfit + facet_grid(Model ~.) -> ps_tmp

ps_tmp

if(export_ppt == TRUE)
{
  ps_tmp %>% 
    export::graph2ppt(append = TRUE, width = export_ppt_width, height = export_ppt_height,
                      file = out_pptx)
}


```
```{r, message= FALSE, warning= FALSE}
ps_16S_rare %>% 
  subset_samples(Model == "Chicken") %>% 
  plot_beta_NRP72(path_group = "interaction(Model, Fermentation, Reactor_Treatment)", tax_rank_plot = "Family", taxrank_glom = "Family", join_cbind = "join") -> p_b_16S

p_b_16S$pcoa + facet_grid(Model ~.) -> ps_tmp

ps_tmp

if(export_ppt == TRUE)
{
  ps_tmp %>% 
    export::graph2ppt(append = TRUE, width = export_ppt_width, height = export_ppt_height,
                      file = out_pptx)
}


p_b_16S$envfit + facet_grid(Model ~.) -> ps_tmp

ps_tmp

if(export_ppt == TRUE)
{
  ps_tmp %>% 
    export::graph2ppt(append = TRUE, width = export_ppt_width, height = export_ppt_height,
                      file = out_pptx)
}


```

```{r, message= FALSE, warning= FALSE}
ps_16S_rare %>% 
  subset_samples(Model == "Human") %>% 
  plot_beta_NRP72(path_group = "interaction(Model, Fermentation, Reactor_Treatment)", tax_rank_plot = "Family", taxrank_glom = "Family", join_cbind = "join") -> p_b_16S

p_b_16S$pcoa + facet_grid(Model ~.) -> ps_tmp

ps_tmp

if(export_ppt == TRUE)
{
  ps_tmp %>% 
    export::graph2ppt(append = TRUE, width = export_ppt_width, height = export_ppt_height,
                      file = out_pptx)
}



p_b_16S$envfit + facet_grid(Model ~.) -> ps_tmp

ps_tmp

if(export_ppt == TRUE)
{
  ps_tmp %>% 
    export::graph2ppt(append = TRUE, width = export_ppt_width, height = export_ppt_height,
                      file = out_pptx)
}


```

```{r, message= FALSE, warning= FALSE}
ps_16S_rare %>% 
  subset_samples(Model == "Chicken") %>% 
  plot_beta_NRP72(path_group = "interaction(Model, Fermentation, Reactor_Treatment)", tax_rank_plot = "Genus", taxrank_glom = "Genus", top_r = 30, join_cbind = "join") -> p_b_16S


p_b_16S$pcoa + facet_grid(Model ~.) -> ps_tmp

ps_tmp

if(export_ppt == TRUE)
{
  ps_tmp %>% 
    export::graph2ppt(append = TRUE, width = export_ppt_width, height = export_ppt_height,
                      file = out_pptx)
}


p_b_16S$envfit + facet_grid(Model ~.) -> ps_tmp

ps_tmp

if(export_ppt == TRUE)
{
  ps_tmp %>% 
    export::graph2ppt(append = TRUE, width = export_ppt_width, height = export_ppt_height,
                      file = out_pptx)
}


```

```{r, message= FALSE, warning= FALSE}
ps_16S_rare %>% 
  subset_samples(Model == "Human") %>% 
  plot_beta_NRP72(path_group = "interaction(Model, Fermentation, Reactor_Treatment)", tax_rank_plot = "Genus", taxrank_glom = "Genus", top_r = 30, join_cbind = "join") -> p_b_16S

p_b_16S$pcoa + facet_grid(Model ~.) -> ps_tmp

ps_tmp

if(export_ppt == TRUE)
{
  ps_tmp %>% 
    export::graph2ppt(append = TRUE, width = export_ppt_width, height = export_ppt_height,
                      file = out_pptx)
}


p_b_16S$envfit + facet_grid(Model ~.) -> ps_tmp

ps_tmp

if(export_ppt == TRUE)
{
  ps_tmp %>% 
    export::graph2ppt(append = TRUE, width = export_ppt_width, height = export_ppt_height,
                      file = out_pptx)
}


```


```{r}
sessionInfo()
```

