---
title: "NTP72 - 16S alpha div"
author: "Florentin Constancias"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document: 
    toc: yes
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# knitr::opts_chunk$set(dev = "ragg_png") # https://ragg.r-lib.org/index.html
knitr::opts_chunk$set(fig.width = 6) #https://r4ds.had.co.nz/graphics-for-communication.html#figure-sizing
knitr::opts_chunk$set(fig.asp = 0.618)
knitr::opts_chunk$set(fig.show = "hold")
knitr::opts_chunk$set(fig.show = "70%")
knitr::opts_chunk$set(fig.align = "center")
```

# Load required packages

```{r,packages,message=FALSE}
library(tidyverse)
# library(phyloseq)
library(speedyseq)
library(ggrepel)
library(here)
# library(microViz)
# library(RColorBrewer)
# library(vegan)
library(randomcoloR)
options(getClass.msg=FALSE) # https://github.com/epurdom/clusterExperiment/issues/66
#this fixes an error message that pops up because the class 'Annotated' is defined in two different packages
```

# Source function

```{r message=FALSE}
rm(list = ls())

source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_taxa_tests.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_normalisation.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_alpha.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_beta.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_heatmap.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_varia.R")

```


```{r}
export_ppt = TRUE
export_ppt_width = NULL
export_ppt_height = NULL
out_pptx = here::here("output/plots.pptx")
```

# Import data + cleaning/ colors/ factors:

```{r}
# "Figures/Rastetics.Rdata" %>%
#   here::here() %>% 
#   load()

load(here::here("Figures/Rastetics.Rdata"))
```

## Data

### 16S:
```{r}
("data/processed/16S/ps_silva_dada2_human_chicken_all_fct_polyferms_090922.RDS") %>% 
  here::here() %>% 
  readRDS() %>% 
  filter_taxa(function(x) sum(x > 0) > 0, TRUE) -> ps_16S
```

```{r}

sample_variables(ps_16S)
```

```{r, message = FALSE}
ps_16S %>%
  # subset_samples(Experiment %!in% c("Mock", "NTC")) %>%
  phyloseq_check_lib_size(data_color = "Experiment", 
                          data_facet = NULL, 
                          nreads_display = 4000, 
                          first_n = 500) -> out

out$df %>%
  dplyr::select(SampleID, Experiment, Model2, LibrarySize) %>%
  # filter(category2 %in% c("feces")) %>%
  DT::datatable()

```
```{r}
out$plot +
  facet_wrap(~ Model2, scales = "free_x") +
  theme_linedraw() + scale_y_log10()
  coord_cartesian(ylim = c(0, 5000), xlim = c(0,600))
```

```{r}
out$df %>% 
  filter(Experiment %!in% c("Mock", "NTC")) %>% 
  filter(LibrarySize < 1000) %>% 
  nrow()
```

60 samples lost 


```{r}
out$df %>% 
  filter(Experiment %!in% c("Mock", "NTC")) %>% 
  filter(LibrarySize < 4000) %>% 
  nrow()
```

62 samples lost 


```{r}
require(parallel)

ps_16S %>%
  subset_samples(Experiment %!in% c("Mock", "NTC")) %>% 
  prune_samples(sample_sums(.)>= 50, .) %>% 
  # filter_taxa(function(x) sum(x > 0) > 0, TRUE) %>% 
  ggrare(step = 50, parallel = TRUE,  se = FALSE, color = "Model2", plot = FALSE) -> rare_curves
```

```{r}
rare_curves +
  theme_classic() +
  facet_wrap( . ~ Model2) +
  # geom_vline(xintercept = 500,
  #            color="red",
  #            linetype="dashed", size=0.25) +
  ylab("ASV Richness") -> plot

plot %>% 
  ggpubr::change_palette(p = ., palette = "lancet") -> plot


```

```{r}
plot + xlim(c(0, 50000))
```


```{r}
plot + xlim(c(0, 4000))
```

Based on those plots I would suggest :
```{r}
depth = 4000

ps_16S %>%
  rarefy_even_depth(sample.size = depth,
                    rngseed = 123) -> physeq_rare

ps_16S %>%
  prune_samples(sample_sums(.)>= depth, .) -> physeq_fil

```


```{r}
# Alpha-diversity:
plot_alpha_div_NRP72 <- function(df, x = "Day_of_Treatment", y = "value",  point_size = 2.5, color = "Treatment", fill  = "Treatment", shape = "Antibiotic", alpha = "Antibiotic_mg.L", facet_formula = paste0("alphadiversiy ~  Model2 "), ylab = "Resistome alpha-diversity", xlab = "Days (Treatment)", measures = c("Observed"), path_group = "interaction(Model, Fermentation, Reactor_Treatment)"){
  
  df %>% 
    pivot_longer(cols = all_of(measures), values_to = "value", names_to = 'alphadiversiy', values_drop_na  = TRUE) %>%
    mutate(alphadiversiy = fct_relevel(alphadiversiy, measures)) -> df_ready
  
  df_ready %>% 
    ggplot(aes_string(x = x, y = y, color = color, fill = fill, shape = shape, alpha = alpha)) + #shape = Fermentation
    geom_point(size = point_size) + 
    geom_line(linetype = 2,  size = 0.5,  aes_string(group = path_group)) +
    labs(y = ylab, x = xlab) +
    scale_color_manual(name = "", values = treat_col,
                       na.value = "black") +
    scale_fill_manual(name = "", values = treat_col,
                      na.value = "black") +
    facet_grid(as.formula(facet_formula), scales = "free", space = "fixed", drop = TRUE) +
    scale_shape_manual(name = "" ,values = antibio_shape, na.value =  17) +
    scale_alpha_discrete(name = "", range=c(0.6, 1), na.value =  0.6) + 
    geom_vline(xintercept = 0, size = 0.5, linetype = 1, color = "grey60") -> p_alpha_both
  
  return(p_alpha_both)
}
```



```{r, message= FALSE, warnings = FALSE, eval = FALSE}
# physeq_rare %>% 
#   filter_taxa(function(x) sum(x > 0) > 0, TRUE) %>% 
#   phyloseq_alphas(phylo = FALSE) -> alpha_16S

physeq_rare %>%  
  estimate_richness(measures = c("Observed", "Chao1", "Shannon")) %>% 
                      plot_alpha_div_NRP72(facet_formula = paste0("alphadiversiy ~  Model ")) 
# alpha_16S %>% 
  # group_by(Model, Fermentation, Antibiotic, Antibiotic_mg.mL, Treatment, Phase, Period) %>% 
  # rstatix::get_summary_stats(Observed, type = "common") %>% 
  # DT::datatable()
```


```{r}
sessionInfo()
```

