---
title: "NTP72 - 16S  gram stain + intrinsic AMR"
author: "Florentin Constancias"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document: 
    toc: yes
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# knitr::opts_chunk$set(dev = "ragg_png") # https://ragg.r-lib.org/index.html
knitr::opts_chunk$set(fig.width = 6) #https://r4ds.had.co.nz/graphics-for-communication.html#figure-sizing
knitr::opts_chunk$set(fig.asp = 0.618)
knitr::opts_chunk$set(fig.show = "hold")
knitr::opts_chunk$set(fig.show = "70%")
knitr::opts_chunk$set(fig.align = "center")
```

# Load required packages

```{r,packages,message=FALSE, include=FALSE}
library(tidyverse)
# library(phyloseq)
library(speedyseq)
library(ggrepel)
library(here)
library(AMR)
# library(RColorBrewer)
# library(vegan)
library(randomcoloR)
options(getClass.msg=FALSE) # https://github.com/epurdom/clusterExperiment/issues/66
#this fixes an error message that pops up because the class 'Annotated' is defined in two different packages
```

# Source function

```{r message=FALSE}
rm(list = ls())

source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_taxa_tests.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_normalisation.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_alpha.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_beta.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_heatmap.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_varia.R")

```


```{r}
export_ppt = TRUE
export_ppt_width = NULL
export_ppt_height = NULL
out_pptx = here::here("output/plots.pptx")
```

# Import data + cleaning/ colors/ factors:

```{r}
# "Figures/Rastetics.Rdata" %>%
#   here::here() %>% 
#   load()

load(here::here("Figures/Rastetics.Rdata"))
```

## Data

### 16S:

```{r}
"data/processed/16S/16S_working_phyloseq.RDS" %>% 
  here::here() %>% 
  readRDS() -> ps_16S
```


```{r}
tibble(ASV = tax_table(ps_16S)[,c("Strain")] %>%  as.vector(),
       Family = tax_table(ps_16S)[,c("Family")] %>%  as.vector(),
       Class = tax_table(ps_16S)[,c("Class")] %>%  as.vector(),
       Phylum = tax_table(ps_16S)[,c("Phylum")] %>%  as.vector(),
       Genus = tax_table(ps_16S)[,c("Genus")] %>%  as.vector(),
       Species = tax_table(ps_16S)[,c("Species")] %>%  as.vector()) -> df
```


```{r}
df %>%  
  # mutate(gram_neg_strain = AMR::mo_gramstain(ASV)) %>% 
  mutate(gram_neg_genus = AMR::mo_gramstain(Genus)) %>% 
  mutate(gram_neg_phylum = AMR::mo_gramstain(Phylum)) %>% 
  mutate(gram_neg_class = AMR::mo_gramstain(Class)) -> gram_df


gram_df  %>% 
  DT::datatable()
```


```{r}
gram_df %>% 
  saveRDS(here::here(("data/processed/16S/16S_based_gram.RDS")))
```


```{r}
df %>% 
  # mutate(intrinsic_genus_ctx = mo_is_intrinsic_resistant(Genus, ab = "CTX")) %>% 
  # mutate(intrinsic_genus_van = mo_is_intrinsic_resistant(Genus, ab = "VAN")) %>% 
  # mutate(intrinsic_family_ctx = mo_is_intrinsic_resistant(Family, ab = "CTX")) %>% 
  # mutate(intrinsic_family_van = mo_is_intrinsic_resistant(Family, ab = "VAN")) %>% 
  # mutate(intrinsic_species_van = mo_is_intrinsic_resistant(Species, ab = "VAN")) %>% 
  # mutate(intrinsic_species_ctx = mo_is_intrinsic_resistant(Species, ab = "CTX")) %>% #-> AMR_df 
  mutate(intrinsic_strain_ctx = mo_is_intrinsic_resistant(ASV, ab = "CTX")) %>%
  mutate(intrinsic_strain_van = mo_is_intrinsic_resistant(ASV, ab = "VAN")) -> AMR_df

AMR_df %>% 
  DT::datatable()
```

```{r}
AMR_df %>% 
  saveRDS(here::here(("data/processed/16S/16S_based_intrinsinc_AMR.RDS")))
```



```{r}
sessionInfo()
```

