---
title: ' 16S GTDB taxonomy data procesing `r Sys.Date()`'
author: "Florentin CONSTANCIAS"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_depth: 4
---

```{r setup, include=FALSE}
rm(list = ls())
# knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, results=FALSE, warning=FALSE, include=TRUE}
require(tidyverse); packageVersion("tidyverse")
require(phyloseq); packageVersion("phyloseq")
```

```{r sourcing, results=FALSE, warning=FALSE, include=TRUE}
outersect <- function(x, y) {
  sort(c(x[!x%in%y],
         y[!y%in%x]))
}

'%!in%' <- function(x,y)!('%in%'(x,y))

# source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_taxa_tests.R") 
source("https://raw.githubusercontent.com/fconstancias/metabaRpipe-source/master/Rscripts/functions.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_normalisation.R") 
# source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_alpha.R") 
# source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_beta.R") 
```


```{r}
"data/processed/16S/16S_working_phyloseq.RDS" %>% 
  here::here() %>% 
  readRDS() -> ps
```

```{r}
ps %>% 
  phyloseq_dada2_tax(
    threshold = 60,
    tryRC = TRUE,
    db = "~/Downloads/GTDB_bac120_arc53_ssu_r207_Genus.fa.gz",
    db_species = "~/Downloads/GTDB_bac120_arc53_ssu_r207_Species.fa.gz",
    nthreads = 6,
    return = TRUE,
    export = FALSE) -> ps_GTDB
```

```{r}
ps_GTDB$physeq %>% 
  phyloseq_get_strains() %>% 
  saveRDS(here::here("data/processed/16S/16S_working_phyloseq_GDTB.RDS"))
```


```{r}
compare_phyloseq_taxonomy(ps, ps_GTDB$physeq %>% phyloseq_get_strains()) %>% 
  data.frame() %>% 
  write_tsv(here::here("data/processed/16S/working_phyloseq_silva_vs_GTDBtax.tsv"))
```


```{r, message = FALSE, warning= FALSE}
sessionInfo()
```
