---
title: "NTP72 - data processing"
author: "Florentin Constancias"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document: 
    toc: yes
    keep_md: yes
---

```{r setup, include=FALSE}
# rm(list = ls())
# knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, results=FALSE, warning=FALSE, include=TRUE}
#install.packages("tidyverse")
require(tidyverse); packageVersion("tidyverse")
require(phyloseq); packageVersion("phyloseq")
```

```{r sourcing, results=FALSE, warning=FALSE, include=TRUE, eval = TRUE}
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_taxa_tests.R") 
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_normalisation.R") 
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_alpha.R") 
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_beta.R") 
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_heatmap.R")
```

```{r}
'%!in%' <- function(x,y)!('%in%'(x,y))
out_pptx = "~/Desktop/16S-human.pptx"
```

```{r, eval = TRUE}
load(url("https://github.com/fconstancias/NRP72-FBT/blob/master/Figures/Rastetics.Rdata?raw=true"))
```


## load data:


```{r, eval = TRUE}
(url("https://github.com/fconstancias/NRP72-FBT/blob/master/data/processed/16S/phyloseq_phylo_aline_human2_donor.RDS?raw=true" )) %>% 
  readRDS() %>% 
  phyloseq_get_strains() %>% 
  subset_samples(Sample_type == "Fecal Sample") -> ps_aline

sample_names(ps_aline) <- "S-238-S238"
```


```{r, eval = TRUE}
source("https://raw.githubusercontent.com/fconstancias/metabaRpipe-source/master/Rscripts/functions.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_normalisation.R") 

(url("https://github.com/fconstancias/NRP72-FBT/blob/master/data/processed/16S/ps_silva_dada2_human_chicken_all_fct_polyferms_051022.RDS?raw=true" )) %>% 
  readRDS() %>% 
  phyloseq_get_strains() %>% 
  # physeq_add_metadata(physeq = .,
  # metadata = ("~/Downloads/16S-NRP72/27.07.2022_metadata_updated_chicken.xlsx") %>%
  # readxl::read_excel(sheet = 1), sample_column = "sample_name") %>% 
  subset_samples(Sample_description %!in% c("TR5-15", "TR4-1")) -> ps_init



```

```{r, eval = TRUE}
ps_init %>%  
  sample_data() %>% 
  data.frame() %>% 
  rownames_to_column("sample_names") -> metadata

```

```{r, eval = TRUE}
phyloseq_combine_objects(ps_init %>% 
                           subset_samples(sample_name != "S-238-S238") ,  
                         ps_aline %>%   filter_taxa(function(x) sum(x > 0) > 0, TRUE), 
                         merge_metada = FALSE) -> ps_all
```

```{r, eval = TRUE}
ps_all %>% 
  physeq_add_metadata(physeq = .,
                      metadata = metadata, 
                      sample_column = "sample_name") %>% 
  phyloseq_get_strains() -> ps_temp

# sample_data(ps_temp) %>% 
#   data.frame()
```

```{r}
# tax_table(ps_init)[,"Strain"]
```


```{r}
# tax_table(ps_temp)[,"Strain"]
```

```{r, eval = TRUE}
ps_temp %>% 
  # microViz::ps_mutate(Antibiotic_mg.L = ifelse(Phase == "Stab", NA, Antibiotic_mg.L))  %>%  sample_data() %>%  data.frame() %>%  select(Antibiotic_mg.L)
  microViz::ps_mutate(Day_of_Treatment = as.double(Day_of_Treatment)) %>% 
  # microViz::ps_mutate(Antibiotic_mg.L = factor(Antibiotic_mg.L, levels = c(NA, 20, 200,90, 600))) %>% 
  microViz::ps_mutate(Treatment = factor(Treatment, levels = c("DONOR","UNTREATED","CTX","CTX+HV292.1","HV292.1","VAN","VAN+CCUG59168", "CCUG59168"
  ))) %>% 
  microViz::ps_mutate(Reactor_Treatment_Dose = factor(Reactor_Treatment_Dose, levels = c("DONOR",  
                                                                                         "IR_UNTREATED",
                                                                                         "CR_UNTREATED",
                                                                                         "TR2_CTX20",
                                                                                         "TR3_CTX20",
                                                                                         "TR3_CTX200",
                                                                                         "TR4_CTX200",
                                                                                         "TR1_CTX+HV292.120",
                                                                                         "TR2_CTX+HV292.120",
                                                                                         "TR3_CTX+HV292.1200",
                                                                                         "TR5_CTX+HV292.1200",
                                                                                         "TR3_HV292.1",
                                                                                         "TR5_HV292.1",
                                                                                         "TR7_HV292.1",
                                                                                         "TR4_VAN90",
                                                                                         "TR2_VAN90",
                                                                                         "TR6_VAN90",
                                                                                         "TR4_VAN600",
                                                                                         "TR2_VAN600",
                                                                                         "TR5_VAN+CCUG5916890",
                                                                                         "TR1_VAN+CCUG5916890",
                                                                                         "TR7_VAN+CCUG5916890",
                                                                                         "TR3_VAN+CCUG59168600",
                                                                                         "TR4_VAN+CCUG59168600",
                                                                                         "TR6_CCUG59168",
                                                                                         "TR5_CCUG59168",
                                                                                         "TR4_CCUG59168"))) %>% 
  microViz::ps_mutate(Reactor_Treatment_Dose_fermentation = paste0(Reactor_Treatment_Dose, "_", Fermentation)) -> ps_temp

ps_temp %>%
  subset_samples(Enrichment == "NotEnriched") %>%
  subset_samples(Experiment %in% c("Cecum", "Continuous")) %>%
  subset_samples(Day_of_Treatment > -6 & Day_of_Treatment <=30 | Reactor == "DONOR") %>% 
  # subset_samples(Model == "Human") %>% 
  # subset_samples(Reactor != "CR" & Model2 == "Chicken1" | Model2 == "Chicken2" &   Reactor %in% c("TR2", "TR3", "TR4", "TR5", "TR6", "TR7", "CR", "DONOR")) %>% 
  subset_samples(Reactor != "IR") %>% 
   filter_taxa(function(x) sum(x > 0) > 0, TRUE)  -> ps_filtered

```

```{r}
ps_filtered %>% 
  saveRDS(here::here("data/processed/16S/16S_working_phyloseq.RDS"))
```

```{r}
sessionInfo()
```

